### ISSUE TITLE
Feature Request: Provide config to auto open terminals when a workspace is opened

### ISSUE THREAD

**Issue by flawiddsouza** [dejmedus/auto-term#2]
Hi, thanks for making this extension. One feature that would be nice to have is if the extension can automatically open terminals for the configured actions when a workspace is opened.

**Comment by dejmedus** [comment]
Hey thanks, that makes sense!

Commands within the "open" action now run on workspace launch when [`Auto Terminal: Run Open Commands On Startup`](https://github.com/dejmedus/auto-term/blob/main/README.md#auto-run-commands-on-startup) is enabled in settings. #3

**Comment by flawiddsouza** [comment]
Thanks for implementing this. It's working great.
